--- #YAML:1.0
name:                Finance-Bank-Smile
version:             0.04
abstract:            Check your Smile bank accounts from Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTML::TableExtract:            0
    Readonly:                      0
    Test::More:                    0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Richard Panman <rpanman@cpan.org>
